### ISSUE TITLE
Scrollbar background not transparent

### ISSUE THREAD

**Issue by thelucid** [rheinfabrik/RFOverlayScrollView#6]
I'm using this in a popover and the scrollbar is not transparent for some reason, any pointers would be most appreciated.

![screen shot 2014-11-04 at 19 22 49](https://cloud.githubusercontent.com/assets/1236447/4906358/3ab5587e-6458-11e4-9c23-c322cf876f09.png)

**Comment by Kapeli** [comment]
I've just encountered this issue but with a regular NSScrollView. It happens because the NSPopover tries to apply a custom styling to elements in Yosemite (i.e. the `NSAppearanceNameVibrantLight` appearance).

To avoid the bug you can set the appearance of the content view of the popover to `NSAppearanceNameAqua`:

```
[view setAppearance:[NSAppearance appearanceNamed:NSAppearanceNameAqua]];
```

I'm not sure if this is a bug or if some designer at Apple thought it would be a good idea to have backgrounds for scrollers that are in popovers.

**Comment by thelucid** [comment]
@Kapeli Thanks, that fixes it. Sorry for the late response!
